sudo: required
services:
  - docker
before_install:
  - docker build -t tomeralony/client-tests -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tomeralony/client-tests npm run test

after_success:
  - docker build -t sturs23/multi-docker-client ./client
  - docker build -t sturs23/multi-docker-nginx ./nginx
  - docker build -t sturs23/multi-docker-server ./server
  - docker build -t sturs23/multi-docker-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sturs23/multi-docker-client
  - docker push sturs23/multi-docker-nginx
  - docker push sturs23/multi-docker-server
  - docker push sturs23/multi-docker-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env-1'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket_name: elasticbeanstalk-us-east-2-954877974658
  bucket_path: docker-multi
